---
# Ansible Playbook to create and manage EC2 servers

- name: Provision servers
  hosts: localhost
  connection: local
  gather_facts: false

  tags:
      - provision

  vars:
      keypair: kkkey
      instance_type: t1.micro
      security_group: mysql
      # bitnami-cloud-us-west-2/lampstack/bitnami-lampstack-5.4.11-1-linux-ubuntu-12.04.1-x86_64-s3.manifest.xml
      image: ami-35dbde5c
      instance_count: 1

  # Provision master

  tasks:
    - name: Launch master
      local_action: ec2 keypair={{ keypair }} group={{ security_group }} instance_type={{ instance_type }} image={{ image }} wait=yes count={{ instance_count }}
      register: ec2master

#    - debug: msg="coordinates {{ ec2master }}"

    # Use with_items to add each instances public IP to a new hostgroup for use in the next play.

    - name: Add new servers to host group
      local_action: add_host name={{ item.public_dns_name }} groups=mysql,master
      with_items: ec2master.instances

    - name: Wait for SSH to be available
      local_action: wait_for host={{ item.public_dns_name }} port=22
      with_items: ec2master.instances

    - name: Wait for full boot
      pause: seconds=15

    - name: Tag instances
      local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
      with_items: ec2master.instances
      args:
        tags:
          Name: anstestmaster

  # Provision slave


    - name: Launch slave
      local_action: ec2 keypair={{ keypair }} group={{ security_group }} instance_type={{ instance_type }} image={{ image }} wait=yes count={{ instance_count }}
      register: ec2slave

    # Use with_items to add each instances public IP to a new hostgroup for use in the next play.

    - name: Add new servers to host group
      local_action: add_host name={{ item.public_dns_name }} groups=mysql,slave
      with_items: ec2slave.instances

    - name: Wait for SSH to be available
      local_action: wait_for host={{ item.public_dns_name }} port=22
      with_items: ec2slave.instances

    - name: Wait for full boot
      pause: seconds=15

    - name: Tag instances
      local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
      with_items: ec2slave.instances
      args:
        tags:
          Name: anstestslave


# Now, configure our new servers

- name: Configure servers
  hosts: mysql
  user: ubuntu
  sudo: yes
  gather_facts: false

  tags:
    - config
    - configure

  tasks:

    - name: Add Percona repository
      action: command apt-key adv --keyserver keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A

    - name: Add Percona step 2
      script: ./repo.sh

    - name: Ensure /etc/mysql/ exists
      file: path=/etc/mysql state=directory mode=755


    - name: Copy my.cnf.sh to remote host and execute it
      script: ./my.cnf.sh

    - name: Install Percona Server
      apt: pkg=percona-server-server-5.6 state=latest install_recommends=no update_cache=yes

    - name: Install python-mysqldb
      apt: pkg=python-mysqldb state=latest install_recommends=no

## Get master coordinates
#
#- name: Get coordinates from master
#  hosts: master
#  user: ubuntu
#  sudo: yes
#  gather_facts: false
#  
#  vars:
#
#      login_host: localhost
#      login_user: root
#      login_password: 
#
# 
#  tasks:
#
#    - name: Get master coordinates
#      mysql_replication: mode=getmaster
#      register: master_coords
#
#    - debug: msg="coordinates {{ master_coords }}"
#
#    - name: Create replication user
#      mysql_user: name=repl password=ication priv=*.*:REPLICATION_CLIENT,REPLICATION_SLAVE state=present
#
## Setup replication on the slave
#
#- name: Setup replication on the slave
#  hosts: slave
#  user: ubuntu
#  sudo: yes
#  gather_facts: false
#
#  vars:
#
#      login_host: localhost
#      login_user: root
#      login_password:
#
#  tasks:
#
#    - name: Change master to
#      mysql_replication: mode=changemaster master_host=ec2master.private_ip master_log_file=master_coords.master_coords.File master_log_pos=master_coords.Position master_user=repl master_password=ication
#      mysql_replication: mode=startslave
