---
# Ansible Playbook to create and manage EC2 servers

- name: Provision servers
  hosts: localhost
  connection: local
  gather_facts: false

  tags:
    - provision

  vars:
    keypair: palominodb
    instance_type: m3.medium
    security_group: tungsten
      # bitnami-cloud-us-west-2/lampstack/bitnami-lampstack-5.4.11-1-linux-ubuntu-12.04.1-x86_64-s3.manifest.xml
#      image: ami-1d8c9574 # htungstenvm
    image: ami-00a11e68 # redhat 6.5, hvm
#      image: ami-75ede230 # paravirtual in us-west-1
    instance_count: 1
    ec2region: "{{ region | default('us-east-1')}}"
    vpc_subnet: subnet-6c46a835
    

  tasks:
    - name: Launch host
      when: ec2region == "us-east-1"
      local_action: ec2 keypair={{ keypair }} group={{ security_group }} instance_type={{ instance_type }} image={{ image }} wait=yes count={{ instance_count }} vpc_subnet_id={{ vpc_subnet }} assign_public_ip=yes
      register: ec2

    - name: Add new servers to host group
      local_action: add_host name={{ item.public_ip }} groups=ec2instances
      with_items: ec2.instances

    - name: Setup EBS volume
      local_action: ec2_vol instance="{{ item.id }}" device_name=/dev/xvdf volume_size=100 region="{{ ec2region }}"
      with_items: ec2.instances
      register: ec2_vol

#    - debug: msg="{{ ec2.instances[0] }}"

    - name: Wait for SSH to be available
      local_action: wait_for host={{ item.public_ip }} port=22
      with_items: ec2.instances

    - name: Wait for full boot
      pause: seconds=15

    - name: Tag instances
      local_action: ec2_tag resource={{ item.id }} region={{ ec2region }} state=present
      with_items: ec2.instances
      args:
        tags:
          Name: '{{ tag }}'

- name: Setup disk
  hosts: ec2instances
  user: ec2-user
  sudo: yes
  gather_facts: false

  tasks:

    - name: Ensure /var/lib/mysql/ exists
      file: path=/var/lib/mysql state=directory mode=755

#    - name: Install xfsprogs
#      apt: pkg=xfsprogs state=latest install_recommends=no update_cache=yes

    - name: Format EBS volume
      filesystem: fstype=ext4 dev=/fstype=ext4 dev=/dev/xvdf

    - name: Mount EBS on given path
      mount: name=/var/lib/mysql src=/dev/xvdf fstype=ext4 opts=noatime,nodiratime state=mounted
 
