---
# Ansible Playbook to create and manage EC2 servers

- name: Provision servers
  hosts: localhost
  connection: local
  gather_facts: false

  tags:
      - provision

  vars:
      keypair: kkkey
      instance_type: m3.xlarge
#      instance_type: i2.4xlarge
      security_group: haproxy
      # bitnami-cloud-us-west-2/lampstack/bitnami-lampstack-5.4.11-1-linux-ubuntu-12.04.1-x86_64-s3.manifest.xml
      image: ami-1d8c9574 # hvm
#      image: ami-018c9568 # paravirtual
      instance_count: 1

  # Provision master

  tasks:
    - name: Launch master
      local_action: ec2 keypair={{ keypair }} group={{ security_group }} instance_type={{ instance_type }} image={{ image }} wait=yes count={{ instance_count }}
      register: ec2master

#    - debug: msg="coordinates {{ ec2master }}"

    # Use with_items to add each instances public IP to a new hostgroup for use in the next play.

    - name: Add new servers to host group
      local_action: add_host name={{ item.public_dns_name }} groups=mysql,master
      with_items: ec2master.instances

    - name: Wait for SSH to be available
      local_action: wait_for host={{ item.public_dns_name }} port=22
      with_items: ec2master.instances

    - name: Wait for full boot
      pause: seconds=15

    - name: Tag instances
      local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
      with_items: ec2master.instances
      args:
        tags:
          Name: '{{ tag }}'


