---
- name: Spin up some EC2 instances
  hosts: 127.0.0.1
  connection: local
  tasks:
#    - name: Create security group
#      local_action:
#        module: ec2_group
#        name: testsg
#        description: Access my-security-group
#        region: us-east-1
#        rules:
#          - proto: tcp
#            from_port: 22
#            to_port: 22
#            cidr_ip: 0.0.0.0/0

    - name: Launch instances
      local_action:
        module: ec2
        region: us-east-1
        keypair: kkkey
        group: mysql
        instance_type: t1.micro
        image: ami-3d128f07
        wait: yes
      register: ec2

    - name: Add instances to host group
      local_action: add_host hostname= groupname=mysql
      with_items: ec2.instances

    - name: Tag instances
      local_action: ec2_tag resource= region=us-east-1 state=present
      with_items: ec2.instances
      args:
        tags:
          Name: anstest

    - name: Give everyone a minute
      pause: minutes=1

